<?php

return [
    // Data untuk provinsi dengan kode 11
    [
        ['nama_bps' => 'SIMEULUE'],
        ['nama_bps' => 'ACEH SINGKIL'],
        ['nama_bps' => 'ACEH SELATAN'],
        ['nama_bps' => 'ACEH TENGGARA'],
        ['nama_bps' => 'ACEH TIMUR'],
        ['nama_bps' => 'ACEH TENGAH'],
        ['nama_bps' => 'ACEH BARAT'],
        ['nama_bps' => 'ACEH BESAR'],
        ['nama_bps' => 'PIDIE'],
        ['nama_bps' => 'BIREUEN'],
        ['nama_bps' => 'ACEH UTARA'],
        ['nama_bps' => 'ACEH BARAT DAYA'],
        ['nama_bps' => 'GAYO LUES'],
        ['nama_bps' => 'ACEH TAMIANG'],
        ['nama_bps' => 'NAGAN RAYA'],
        ['nama_bps' => 'ACEH JAYA'],
        ['nama_bps' => 'BENER MERIAH'],
        ['nama_bps' => 'PIDIE JAYA'],
        ['nama_bps' => 'BANDA ACEH'],
        ['nama_bps' => 'SABANG'],
        ['nama_bps' => 'LANGSA'],
        ['nama_bps' => 'LHOKSEUMAWE'],
        ['nama_bps' => 'SUBULUSSALAM'],
    ],
    // Data untuk provinsi dengan kode 12
    [
        ['nama_bps' => 'NIAS'],
        ['nama_bps' => 'MANDAILING NATAL'],
        ['nama_bps' => 'TAPANULI SELATAN'],
        ['nama_bps' => 'TAPANULI TENGAH'],
        ['nama_bps' => 'TAPANULI UTARA'],
        ['nama_bps' => 'TOBA SAMOSIR'],
        ['nama_bps' => 'LABUHAN BATU'],
        ['nama_bps' => 'ASAHAN'],
        ['nama_bps' => 'SIMALUNGUN'],
        ['nama_bps' => 'DAIRI'],
        ['nama_bps' => 'KARO'],
        ['nama_bps' => 'DELI SERDANG'],
        ['nama_bps' => 'LANGKAT'],
        ['nama_bps' => 'NIAS SELATAN'],
        ['nama_bps' => 'HUMBANG HASUNDUTAN'],
        ['nama_bps' => 'PAKPAK BHARAT'],
        ['nama_bps' => 'SAMOSIR'],
        ['nama_bps' => 'SERDANG BEDAGAI'],
        ['nama_bps' => 'BATU BARA'],
        ['nama_bps' => 'PADANG LAWAS UTARA'],
        ['nama_bps' => 'PADANG LAWAS'],
        ['nama_bps' => 'LABUHAN BATU SELATAN'],
        ['nama_bps' => 'LABUHAN BATU UTARA'],
        ['nama_bps' => 'NIAS UTARA'],
        ['nama_bps' => 'NIAS BARAT'],
        ['nama_bps' => 'SIBOLGA'],
        ['nama_bps' => 'TANJUNG BALAI'],
        ['nama_bps' => 'PEMATANG SIANTAR'],
        ['nama_bps' => 'TEBING TINGGI'],
        ['nama_bps' => 'MEDAN'],
        ['nama_bps' => 'BINJAI'],
        ['nama_bps' => 'PADANGSIDIMPUAN'],
        ['nama_bps' => 'GUNUNGSITOLI'],
    ],
    // Data untuk provinsi dengan kode 13
    [
        ['nama_bps' => 'KEPULAUAN MENTAWAI'],
        ['nama_bps' => 'PESISIR SELATAN'],
        ['nama_bps' => 'SOLOK'],
        ['nama_bps' => 'SIJUNJUNG'],
        ['nama_bps' => 'TANAH DATAR'],
        ['nama_bps' => 'PADANG PARIAMAN'],
        ['nama_bps' => 'AGAM'],
        ['nama_bps' => 'LIMA PULUH KOTA'],
        ['nama_bps' => 'PASAMAN'],
        ['nama_bps' => 'SOLOK SELATAN'],
        ['nama_bps' => 'DHARMASRAYA'],
        ['nama_bps' => 'PASAMAN BARAT'],
        ['nama_bps' => 'PADANG'],
        ['nama_bps' => 'SOLOK'],
        ['nama_bps' => 'SAWAH LUNTO'],
        ['nama_bps' => 'PADANG PANJANG'],
        ['nama_bps' => 'BUKITTINGGI'],
        ['nama_bps' => 'PAYAKUMBUH'],
        ['nama_bps' => 'PARIAMAN'],
    ],
    // Data untuk provinsi dengan kode 14
    [
        ['nama_bps' => 'KUANTAN SINGINGI'],
        ['nama_bps' => 'INDRAGIRI HULU'],
        ['nama_bps' => 'INDRAGIRI HILIR'],
        ['nama_bps' => 'PELALAWAN'],
        ['nama_bps' => 'S I A K'],
        ['nama_bps' => 'KAMPAR'],
        ['nama_bps' => 'ROKAN HULU'],
        ['nama_bps' => 'BENGKALIS'],
        ['nama_bps' => 'ROKAN HILIR'],
        ['nama_bps' => 'KEPULAUAN MERANTI'],
        ['nama_bps' => 'PEKANBARU'],
        ['nama_bps' => 'D U M A I'],
    ],
    // Data untuk provinsi dengan kode 15
    [
        ['nama_bps' => 'KERINCI'],
        ['nama_bps' => 'MERANGIN'],
        ['nama_bps' => 'SAROLANGUN'],
        ['nama_bps' => 'BATANG HARI'],
        ['nama_bps' => 'MUARO JAMBI'],
        ['nama_bps' => 'TANJUNG JABUNG TIMUR'],
        ['nama_bps' => 'TANJUNG JABUNG BARAT'],
        ['nama_bps' => 'TEBO'],
        ['nama_bps' => 'BUNGO'],
        ['nama_bps' => 'JAMBI'],
        ['nama_bps' => 'SUNGAI PENUH'],
    ],
    // Data untuk provinsi dengan kode 16
    [
        ['nama_bps' => 'OGAN KOMERING ULU'],
        ['nama_bps' => 'OGAN KOMERING ILIR'],
        ['nama_bps' => 'MUARA ENIM'],
        ['nama_bps' => 'LAHAT'],
        ['nama_bps' => 'MUSI RAWAS'],
        ['nama_bps' => 'MUSI BANYUASIN'],
        ['nama_bps' => 'BANYU ASIN'],
        ['nama_bps' => 'OGAN KOMERING ULU SELATAN'],
        ['nama_bps' => 'OGAN KOMERING ULU TIMUR'],
        ['nama_bps' => 'OGAN ILIR'],
        ['nama_bps' => 'EMPAT LAWANG'],
        ['nama_bps' => 'PENUKAL ABAB LEMATANG ILIR'],
        ['nama_bps' => 'MUSI RAWAS UTARA'],
        ['nama_bps' => 'PALEMBANG'],
        ['nama_bps' => 'PRABUMULIH'],
        ['nama_bps' => 'PAGAR ALAM'],
        ['nama_bps' => 'LUBUKLINGGAU'],
    ],
    // Data untuk provinsi dengan kode 17
    [
        ['nama_bps' => 'BENGKULU SELATAN'],
        ['nama_bps' => 'REJANG LEBONG'],
        ['nama_bps' => 'BENGKULU UTARA'],
        ['nama_bps' => 'KAUR'],
        ['nama_bps' => 'SELUMA'],
        ['nama_bps' => 'MUKOMUKO'],
        ['nama_bps' => 'LEBONG'],
        ['nama_bps' => 'KEPAHIANG'],
        ['nama_bps' => 'BENGKULU TENGAH'],
        ['nama_bps' => 'BENGKULU'],
    ],
    // Data untuk provinsi dengan kode 18
    [
        ['nama_bps' => 'LAMPUNG BARAT'],
        ['nama_bps' => 'TANGGAMUS'],
        ['nama_bps' => 'LAMPUNG SELATAN'],
        ['nama_bps' => 'LAMPUNG TIMUR'],
        ['nama_bps' => 'LAMPUNG TENGAH'],
        ['nama_bps' => 'LAMPUNG UTARA'],
        ['nama_bps' => 'WAY KANAN'],
        ['nama_bps' => 'TULANGBAWANG'],
        ['nama_bps' => 'PESAWARAN'],
        ['nama_bps' => 'PRINGSEWU'],
        ['nama_bps' => 'MESUJI'],
        ['nama_bps' => 'TULANG BAWANG BARAT'],
        ['nama_bps' => 'PESISIR BARAT'],
        ['nama_bps' => 'BANDAR LAMPUNG'],
        ['nama_bps' => 'METRO'],
    ],
    // Data untuk provinsi dengan kode 19
    [
        ['nama_bps' => 'BANGKA'],
        ['nama_bps' => 'BELITUNG'],
        ['nama_bps' => 'BANGKA BARAT'],
        ['nama_bps' => 'BANGKA TENGAH'],
        ['nama_bps' => 'BANGKA SELATAN'],
        ['nama_bps' => 'BELITUNG TIMUR'],
        ['nama_bps' => 'PANGKALPINANG'],
    ],
    // Data untuk provinsi dengan kode 21
    [
        ['nama_bps' => 'KARIMUN'],
        ['nama_bps' => 'BINTAN'],
        ['nama_bps' => 'NATUNA'],
        ['nama_bps' => 'LINGGA'],
        ['nama_bps' => 'KEPULAUAN ANAMBAS'],
        ['nama_bps' => 'B A T A M'],
        ['nama_bps' => 'TANJUNG PINANG'],
    ],
    // Data untuk provinsi dengan kode 31
    [
        ['nama_bps' => 'KEPULAUAN SERIBU'],
        ['nama_bps' => 'JAKARTA SELATAN'],
        ['nama_bps' => 'JAKARTA TIMUR'],
        ['nama_bps' => 'JAKARTA PUSAT'],
        ['nama_bps' => 'JAKARTA BARAT'],
        ['nama_bps' => 'JAKARTA UTARA'],
    ],
    // Data untuk provinsi dengan kode 32
    [
        ['nama_bps' => 'BOGOR'],
        ['nama_bps' => 'SUKABUMI'],
        ['nama_bps' => 'CIANJUR'],
        ['nama_bps' => 'BANDUNG'],
        ['nama_bps' => 'GARUT'],
        ['nama_bps' => 'TASIKMALAYA'],
        ['nama_bps' => 'CIAMIS'],
        ['nama_bps' => 'KUNINGAN'],
        ['nama_bps' => 'CIREBON'],
        ['nama_bps' => 'MAJALENGKA'],
        ['nama_bps' => 'SUMEDANG'],
        ['nama_bps' => 'INDRAMAYU'],
        ['nama_bps' => 'SUBANG'],
        ['nama_bps' => 'PURWAKARTA'],
        ['nama_bps' => 'KARAWANG'],
        ['nama_bps' => 'BEKASI'],
        ['nama_bps' => 'BANDUNG BARAT'],
        ['nama_bps' => 'PANGANDARAN'],
        ['nama_bps' => 'BOGOR'],
        ['nama_bps' => 'SUKABUMI'],
        ['nama_bps' => 'BANDUNG'],
        ['nama_bps' => 'CIREBON'],
        ['nama_bps' => 'BEKASI'],
        ['nama_bps' => 'DEPOK'],
        ['nama_bps' => 'CIMAHI'],
        ['nama_bps' => 'TASIKMALAYA'],
        ['nama_bps' => 'BANJAR'],
    ],
    // Data untuk provinsi dengan kode 33
    [
        ['nama_bps' => 'CILACAP'],
        ['nama_bps' => 'BANYUMAS'],
        ['nama_bps' => 'PURBALINGGA'],
        ['nama_bps' => 'BANJARNEGARA'],
        ['nama_bps' => 'KEBUMEN'],
        ['nama_bps' => 'PURWOREJO'],
        ['nama_bps' => 'WONOSOBO'],
        ['nama_bps' => 'MAGELANG'],
        ['nama_bps' => 'BOYOLALI'],
        ['nama_bps' => 'KLATEN'],
        ['nama_bps' => 'SUKOHARJO'],
        ['nama_bps' => 'WONOGIRI'],
        ['nama_bps' => 'KARANGANYAR'],
        ['nama_bps' => 'SRAGEN'],
        ['nama_bps' => 'GROBOGAN'],
        ['nama_bps' => 'BLORA'],
        ['nama_bps' => 'REMBANG'],
        ['nama_bps' => 'PATI'],
        ['nama_bps' => 'KUDUS'],
        ['nama_bps' => 'JEPARA'],
        ['nama_bps' => 'DEMAK'],
        ['nama_bps' => 'SEMARANG'],
        ['nama_bps' => 'TEMANGGUNG'],
        ['nama_bps' => 'KENDAL'],
        ['nama_bps' => 'BATANG'],
        ['nama_bps' => 'PEKALONGAN'],
        ['nama_bps' => 'PEMALANG'],
        ['nama_bps' => 'TEGAL'],
        ['nama_bps' => 'BREBES'],
        ['nama_bps' => 'MAGELANG'],
        ['nama_bps' => 'SURAKARTA'],
        ['nama_bps' => 'SALATIGA'],
        ['nama_bps' => 'SEMARANG'],
        ['nama_bps' => 'PEKALONGAN'],
        ['nama_bps' => 'TEGAL'],
    ],
    // Data untuk provinsi dengan kode 34
    [
        ['nama_bps' => 'KULON PROGO'],
        ['nama_bps' => 'BANTUL'],
        ['nama_bps' => 'GUNUNGKIDUL'],
        ['nama_bps' => 'SLEMAN'],
        ['nama_bps' => 'YOGYAKARTA'],
    ],
    // Data untuk provinsi dengan kode 35
    [
        ['nama_bps' => 'PACITAN'],
        ['nama_bps' => 'PONOROGO'],
        ['nama_bps' => 'TRENGGALEK'],
        ['nama_bps' => 'TULUNGAGUNG'],
        ['nama_bps' => 'BLITAR'],
        ['nama_bps' => 'KEDIRI'],
        ['nama_bps' => 'MALANG'],
        ['nama_bps' => 'LUMAJANG'],
        ['nama_bps' => 'JEMBER'],
        ['nama_bps' => 'BANYUWANGI'],
        ['nama_bps' => 'BONDOWOSO'],
        ['nama_bps' => 'SITUBONDO'],
        ['nama_bps' => 'PROBOLINGGO'],
        ['nama_bps' => 'PASURUAN'],
        ['nama_bps' => 'SIDOARJO'],
        ['nama_bps' => 'MOJOKERTO'],
        ['nama_bps' => 'JOMBANG'],
        ['nama_bps' => 'NGANJUK'],
        ['nama_bps' => 'MADIUN'],
        ['nama_bps' => 'MAGETAN'],
        ['nama_bps' => 'NGAWI'],
        ['nama_bps' => 'BOJONEGORO'],
        ['nama_bps' => 'TUBAN'],
        ['nama_bps' => 'LAMONGAN'],
        ['nama_bps' => 'GRESIK'],
        ['nama_bps' => 'BANGKALAN'],
        ['nama_bps' => 'SAMPANG'],
        ['nama_bps' => 'PAMEKASAN'],
        ['nama_bps' => 'SUMENEP'],
        ['nama_bps' => 'KEDIRI'],
        ['nama_bps' => 'BLITAR'],
        ['nama_bps' => 'MALANG'],
        ['nama_bps' => 'PROBOLINGGO'],
        ['nama_bps' => 'PASURUAN'],
        ['nama_bps' => 'MOJOKERTO'],
        ['nama_bps' => 'MADIUN'],
        ['nama_bps' => 'SURABAYA'],
        ['nama_bps' => 'BATU'],
    ],
    // Data untuk provinsi dengan kode 36
    [
        ['nama_bps' => 'PANDEGLANG'],
        ['nama_bps' => 'LEBAK'],
        ['nama_bps' => 'TANGERANG'],
        ['nama_bps' => 'SERANG'],
        ['nama_bps' => 'TANGERANG'],
        ['nama_bps' => 'CILEGON'],
        ['nama_bps' => 'SERANG'],
        ['nama_bps' => 'TANGERANG SELATAN'],
    ],
    // Data untuk provinsi dengan kode 51
    [
        ['nama_bps' => 'JEMBRANA'],
        ['nama_bps' => 'TABANAN'],
        ['nama_bps' => 'BADUNG'],
        ['nama_bps' => 'GIANYAR'],
        ['nama_bps' => 'KLUNGKUNG'],
        ['nama_bps' => 'BANGLI'],
        ['nama_bps' => 'KARANGASEM'],
        ['nama_bps' => 'BULELENG'],
        ['nama_bps' => 'DENPASAR'],
    ],
    // Data untuk provinsi dengan kode 52
    [
        ['nama_bps' => 'LOMBOK BARAT'],
        ['nama_bps' => 'LOMBOK TENGAH'],
        ['nama_bps' => 'LOMBOK TIMUR'],
        ['nama_bps' => 'SUMBAWA'],
        ['nama_bps' => 'DOMPU'],
        ['nama_bps' => 'BIMA'],
        ['nama_bps' => 'SUMBAWA BARAT'],
        ['nama_bps' => 'LOMBOK UTARA'],
        ['nama_bps' => 'MATARAM'],
        ['nama_bps' => 'BIMA'],
    ],
    // Data untuk provinsi dengan kode 53
    [
        ['nama_bps' => 'SUMBA BARAT'],
        ['nama_bps' => 'SUMBA TIMUR'],
        ['nama_bps' => 'KUPANG'],
        ['nama_bps' => 'TIMOR TENGAH SELATAN'],
        ['nama_bps' => 'TIMOR TENGAH UTARA'],
        ['nama_bps' => 'BELU'],
        ['nama_bps' => 'ALOR'],
        ['nama_bps' => 'LEMBATA'],
        ['nama_bps' => 'FLORES TIMUR'],
        ['nama_bps' => 'SIKKA'],
        ['nama_bps' => 'ENDE'],
        ['nama_bps' => 'NGADA'],
        ['nama_bps' => 'MANGGARAI'],
        ['nama_bps' => 'ROTE NDAO'],
        ['nama_bps' => 'MANGGARAI BARAT'],
        ['nama_bps' => 'SUMBA TENGAH'],
        ['nama_bps' => 'SUMBA BARAT DAYA'],
        ['nama_bps' => 'NAGEKEO'],
        ['nama_bps' => 'MANGGARAI TIMUR'],
        ['nama_bps' => 'SABU RAIJUA'],
        ['nama_bps' => 'MALAKA'],
        ['nama_bps' => 'KUPANG'],
    ],
    // Data untuk provinsi dengan kode 61
    [
        ['nama_bps' => 'SAMBAS'],
        ['nama_bps' => 'BENGKAYANG'],
        ['nama_bps' => 'LANDAK'],
        ['nama_bps' => 'MEMPAWAH'],
        ['nama_bps' => 'SANGGAU'],
        ['nama_bps' => 'KETAPANG'],
        ['nama_bps' => 'SINTANG'],
        ['nama_bps' => 'KAPUAS HULU'],
        ['nama_bps' => 'SEKADAU'],
        ['nama_bps' => 'MELAWI'],
        ['nama_bps' => 'KAYONG UTARA'],
        ['nama_bps' => 'KUBU RAYA'],
        ['nama_bps' => 'PONTIANAK'],
        ['nama_bps' => 'SINGKAWANG'],
    ],
    // Data untuk provinsi dengan kode 62
    [
        ['nama_bps' => 'KOTAWARINGIN BARAT'],
        ['nama_bps' => 'KOTAWARINGIN TIMUR'],
        ['nama_bps' => 'KAPUAS'],
        ['nama_bps' => 'BARITO SELATAN'],
        ['nama_bps' => 'BARITO UTARA'],
        ['nama_bps' => 'SUKAMARA'],
        ['nama_bps' => 'LAMANDAU'],
        ['nama_bps' => 'SERUYAN'],
        ['nama_bps' => 'KATINGAN'],
        ['nama_bps' => 'PULANG PISAU'],
        ['nama_bps' => 'GUNUNG MAS'],
        ['nama_bps' => 'BARITO TIMUR'],
        ['nama_bps' => 'MURUNG RAYA'],
        ['nama_bps' => 'PALANGKA RAYA'],
    ],
    // Data untuk provinsi dengan kode 63
    [
        ['nama_bps' => 'TANAH LAUT'],
        ['nama_bps' => 'KOTABARU'],
        ['nama_bps' => 'BANJAR'],
        ['nama_bps' => 'BARITO KUALA'],
        ['nama_bps' => 'TAPIN'],
        ['nama_bps' => 'HULU SUNGAI SELATAN'],
        ['nama_bps' => 'HULU SUNGAI TENGAH'],
        ['nama_bps' => 'HULU SUNGAI UTARA'],
        ['nama_bps' => 'TABALONG'],
        ['nama_bps' => 'TANAH BUMBU'],
        ['nama_bps' => 'BALANGAN'],
        ['nama_bps' => 'BANJARMASIN'],
        ['nama_bps' => 'BANJAR BARU'],
    ],
    // Data untuk provinsi dengan kode 64
    [
        ['nama_bps' => 'PASER'],
        ['nama_bps' => 'KUTAI BARAT'],
        ['nama_bps' => 'KUTAI KARTANEGARA'],
        ['nama_bps' => 'KUTAI TIMUR'],
        ['nama_bps' => 'BERAU'],
        ['nama_bps' => 'PENAJAM PASER UTARA'],
        ['nama_bps' => 'MAHAKAM HULU'],
        ['nama_bps' => 'BALIKPAPAN'],
        ['nama_bps' => 'SAMARINDA'],
        ['nama_bps' => 'BONTANG'],
    ],
    // Data untuk provinsi dengan kode 65
    [
        ['nama_bps' => 'MALINAU'],
        ['nama_bps' => 'BULUNGAN'],
        ['nama_bps' => 'TANA TIDUNG'],
        ['nama_bps' => 'NUNUKAN'],
        ['nama_bps' => 'TARAKAN'],
    ],
    // Data untuk provinsi dengan kode 71
    [
        ['nama_bps' => 'BOLAANG MONGONDOW'],
        ['nama_bps' => 'MINAHASA'],
        ['nama_bps' => 'KEPULAUAN SANGIHE'],
        ['nama_bps' => 'KEPULAUAN TALAUD'],
        ['nama_bps' => 'MINAHASA SELATAN'],
        ['nama_bps' => 'MINAHASA UTARA'],
        ['nama_bps' => 'BOLAANG MONGONDOW UTARA'],
        ['nama_bps' => 'SIAU TAGULANDANG BIARO'],
        ['nama_bps' => 'MINAHASA TENGGARA'],
        ['nama_bps' => 'BOLAANG MONGONDOW SELATAN'],
        ['nama_bps' => 'BOLAANG MONGONDOW TIMUR'],
        ['nama_bps' => 'MANADO'],
        ['nama_bps' => 'BITUNG'],
        ['nama_bps' => 'TOMOHON'],
        ['nama_bps' => 'KOTAMOBAGU'],
    ],
    // Data untuk provinsi dengan kode 72
    [
        ['nama_bps' => 'BANGGAI KEPULAUAN'],
        ['nama_bps' => 'BANGGAI'],
        ['nama_bps' => 'MOROWALI'],
        ['nama_bps' => 'POSO'],
        ['nama_bps' => 'DONGGALA'],
        ['nama_bps' => 'TOLI-TOLI'],
        ['nama_bps' => 'BUOL'],
        ['nama_bps' => 'PARIGI MOUTONG'],
        ['nama_bps' => 'TOJO UNA-UNA'],
        ['nama_bps' => 'SIGI'],
        ['nama_bps' => 'BANGGAI LAUT'],
        ['nama_bps' => 'MOROWALI UTARA'],
        ['nama_bps' => 'PALU'],
    ],
    // Data untuk provinsi dengan kode 73
    [
        ['nama_bps' => 'KEPULAUAN SELAYAR'],
        ['nama_bps' => 'BULUKUMBA'],
        ['nama_bps' => 'BANTAENG'],
        ['nama_bps' => 'JENEPONTO'],
        ['nama_bps' => 'TAKALAR'],
        ['nama_bps' => 'GOWA'],
        ['nama_bps' => 'SINJAI'],
        ['nama_bps' => 'MAROS'],
        ['nama_bps' => 'PANGKAJENE DAN KEPULAUAN'],
        ['nama_bps' => 'BARRU'],
        ['nama_bps' => 'BONE'],
        ['nama_bps' => 'SOPPENG'],
        ['nama_bps' => 'WAJO'],
        ['nama_bps' => 'SIDENRENG RAPPANG'],
        ['nama_bps' => 'PINRANG'],
        ['nama_bps' => 'ENREKANG'],
        ['nama_bps' => 'LUWU'],
        ['nama_bps' => 'TANA TORAJA'],
        ['nama_bps' => 'LUWU UTARA'],
        ['nama_bps' => 'LUWU TIMUR'],
        ['nama_bps' => 'TORAJA UTARA'],
        ['nama_bps' => 'MAKASSAR'],
        ['nama_bps' => 'PAREPARE'],
        ['nama_bps' => 'PALOPO'],
    ],
    // Data untuk provinsi dengan kode 74
    [
        ['nama_bps' => 'BUTON'],
        ['nama_bps' => 'MUNA'],
        ['nama_bps' => 'KONAWE'],
        ['nama_bps' => 'KOLAKA'],
        ['nama_bps' => 'KONAWE SELATAN'],
        ['nama_bps' => 'BOMBANA'],
        ['nama_bps' => 'WAKATOBI'],
        ['nama_bps' => 'KOLAKA UTARA'],
        ['nama_bps' => 'BUTON UTARA'],
        ['nama_bps' => 'KONAWE UTARA'],
        ['nama_bps' => 'KOLAKA TIMUR'],
        ['nama_bps' => 'KONAWE KEPULAUAN'],
        ['nama_bps' => 'MUNA BARAT'],
        ['nama_bps' => 'BUTON TENGAH'],
        ['nama_bps' => 'BUTON SELATAN'],
        ['nama_bps' => 'KENDARI'],
        ['nama_bps' => 'BAUBAU'],
    ],
    // Data untuk provinsi dengan kode 75
    [
        ['nama_bps' => 'BOALEMO'],
        ['nama_bps' => 'GORONTALO'],
        ['nama_bps' => 'POHUWATO'],
        ['nama_bps' => 'BONE BOLANGO'],
        ['nama_bps' => 'GORONTALO UTARA'],
        ['nama_bps' => 'GORONTALO'],
    ],
    // Data untuk provinsi dengan kode 76
    [
        ['nama_bps' => 'MAJENE'],
        ['nama_bps' => 'POLEWALI MANDAR'],
        ['nama_bps' => 'MAMASA'],
        ['nama_bps' => 'MAMUJU'],
        ['nama_bps' => 'PASANGKAYU'],
        ['nama_bps' => 'MAMUJU TENGAH'],
    ],
    // Data untuk provinsi dengan kode 81
    [
        ['nama_bps' => 'KEPULAUAN TANIMBAR'],
        ['nama_bps' => 'MALUKU TENGGARA'],
        ['nama_bps' => 'MALUKU TENGAH'],
        ['nama_bps' => 'BURU'],
        ['nama_bps' => 'KEPULAUAN ARU'],
        ['nama_bps' => 'SERAM BAGIAN BARAT'],
        ['nama_bps' => 'SERAM BAGIAN TIMUR'],
        ['nama_bps' => 'MALUKU BARAT DAYA'],
        ['nama_bps' => 'BURU SELATAN'],
        ['nama_bps' => 'AMBON'],
        ['nama_bps' => 'TUAL'],
    ],
    // Data untuk provinsi dengan kode 82
    [
        ['nama_bps' => 'HALMAHERA BARAT'],
        ['nama_bps' => 'HALMAHERA TENGAH'],
        ['nama_bps' => 'KEPULAUAN SULA'],
        ['nama_bps' => 'HALMAHERA SELATAN'],
        ['nama_bps' => 'HALMAHERA UTARA'],
        ['nama_bps' => 'HALMAHERA TIMUR'],
        ['nama_bps' => 'PULAU MOROTAI'],
        ['nama_bps' => 'PULAU TALIABU'],
        ['nama_bps' => 'TERNATE'],
        ['nama_bps' => 'TIDORE KEPULAUAN'],
    ],
    // Data untuk provinsi dengan kode 91
    [
        ['nama_bps' => 'FAKFAK'],
        ['nama_bps' => 'KAIMANA'],
        ['nama_bps' => 'TELUK WONDAMA'],
        ['nama_bps' => 'TELUK BINTUNI'],
        ['nama_bps' => 'MANOKWARI'],
        ['nama_bps' => 'SORONG SELATAN'],
        ['nama_bps' => 'SORONG'],
        ['nama_bps' => 'RAJA AMPAT'],
        ['nama_bps' => 'TAMBRAUW'],
        ['nama_bps' => 'MAYBRAT'],
        ['nama_bps' => 'MANOKWARI SELATAN'],
        ['nama_bps' => 'PEGUNUNGAN ARFAK'],
        ['nama_bps' => 'SORONG'],
    ],
    // Data untuk provinsi dengan kode 92
    [
    ],
    // Data untuk provinsi dengan kode 94
    [
        ['nama_bps' => 'MERAUKE'],
        ['nama_bps' => 'JAYAWIJAYA'],
        ['nama_bps' => 'JAYAPURA'],
        ['nama_bps' => 'NABIRE'],
        ['nama_bps' => 'KEPULAUAN YAPEN'],
        ['nama_bps' => 'BIAK NUMFOR'],
        ['nama_bps' => 'PANIAI'],
        ['nama_bps' => 'PUNCAK JAYA'],
        ['nama_bps' => 'MIMIKA'],
        ['nama_bps' => 'BOVEN DIGOEL'],
        ['nama_bps' => 'MAPPI'],
        ['nama_bps' => 'ASMAT'],
        ['nama_bps' => 'YAHUKIMO'],
        ['nama_bps' => 'PEGUNUNGAN BINTANG'],
        ['nama_bps' => 'TOLIKARA'],
        ['nama_bps' => 'SARMI'],
        ['nama_bps' => 'KEEROM'],
        ['nama_bps' => 'WAROPEN'],
        ['nama_bps' => 'SUPIORI'],
        ['nama_bps' => 'MAMBERAMO RAYA'],
        ['nama_bps' => 'NDUGA'],
        ['nama_bps' => 'LANNY JAYA'],
        ['nama_bps' => 'MAMBERAMO TENGAH'],
        ['nama_bps' => 'YALIMO'],
        ['nama_bps' => 'PUNCAK'],
        ['nama_bps' => 'DOGIYAI'],
        ['nama_bps' => 'INTAN JAYA'],
        ['nama_bps' => 'DEIYAI'],
        ['nama_bps' => 'JAYAPURA'],
    ],
    // Data untuk provinsi dengan kode 95
    [
    ],
    // Data untuk provinsi dengan kode 96
    [
    ],
    // Data untuk provinsi dengan kode 97
    [
    ],
];
