<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'nama' => 'Aruba', 'iso1' => 'ABW', 'iso2' => 'AW', 'flag' => 'AW.png'],
            ['id' => 2, 'nama' => 'Afghanistan', 'iso1' => 'AFG', 'iso2' => 'AF', 'flag' => 'AF.png'],
            ['id' => 3, 'nama' => 'Angola', 'iso1' => 'AGO', 'iso2' => 'AO', 'flag' => 'AO.png'],
            ['id' => 4, 'nama' => 'Anguilla', 'iso1' => 'AIA', 'iso2' => 'AI', 'flag' => 'AI.png'],
            ['id' => 5, 'nama' => 'Åland', 'iso1' => 'ALA', 'iso2' => 'AX', 'flag' => 'AX.png'],
            ['id' => 6, 'nama' => 'Albania', 'iso1' => 'ALB', 'iso2' => 'AL', 'flag' => 'AL.png'],
            ['id' => 7, 'nama' => 'Andorra', 'iso1' => 'AND', 'iso2' => 'AD', 'flag' => 'AD.png'],
            ['id' => 8, 'nama' => 'United Arab Emirates', 'iso1' => 'ARE', 'iso2' => 'AE', 'flag' => 'AE.png'],
            ['id' => 9, 'nama' => 'Argentina', 'iso1' => 'ARG', 'iso2' => 'AR', 'flag' => 'AR.png'],
            ['id' => 10, 'nama' => 'Armenia', 'iso1' => 'ARM', 'iso2' => 'AM', 'flag' => 'AM.png'],
            ['id' => 11, 'nama' => 'American Samoa', 'iso1' => 'ASM', 'iso2' => 'AS', 'flag' => 'AS.png'],
            ['id' => 12, 'nama' => 'Antarctica', 'iso1' => 'ATA', 'iso2' => 'AQ', 'flag' => 'AQ.png'],
            ['id' => 13, 'nama' => 'French Southern Territories', 'iso1' => 'ATF', 'iso2' => 'TF', 'flag' => 'TF.png'],
            ['id' => 14, 'nama' => 'Antigua and Barbuda', 'iso1' => 'ATG', 'iso2' => 'AG', 'flag' => 'AG.png'],
            ['id' => 15, 'nama' => 'Australia', 'iso1' => 'AUS', 'iso2' => 'AU', 'flag' => 'AU.png'],
            ['id' => 16, 'nama' => 'Austria', 'iso1' => 'AUT', 'iso2' => 'AT', 'flag' => 'AT.png'],
            ['id' => 17, 'nama' => 'Azerbaijan', 'iso1' => 'AZE', 'iso2' => 'AZ', 'flag' => 'AZ.png'],
            ['id' => 18, 'nama' => 'Burundi', 'iso1' => 'BDI', 'iso2' => 'BI', 'flag' => 'BI.png'],
            ['id' => 19, 'nama' => 'Belgium', 'iso1' => 'BEL', 'iso2' => 'BE', 'flag' => 'BE.png'],
            ['id' => 20, 'nama' => 'Benin', 'iso1' => 'BEN', 'iso2' => 'BJ', 'flag' => 'BJ.png'],
            ['id' => 21, 'nama' => 'Bonaire', 'iso1' => 'BES', 'iso2' => 'BQ', 'flag' => 'BQ.png'],
            ['id' => 22, 'nama' => 'Burkina Faso', 'iso1' => 'BFA', 'iso2' => 'BF', 'flag' => 'BF.png'],
            ['id' => 23, 'nama' => 'Bangladesh', 'iso1' => 'BGD', 'iso2' => 'BD', 'flag' => 'BD.png'],
            ['id' => 24, 'nama' => 'Bulgaria', 'iso1' => 'BGR', 'iso2' => 'BG', 'flag' => 'BG.png'],
            ['id' => 25, 'nama' => 'Bahrain', 'iso1' => 'BHR', 'iso2' => 'BH', 'flag' => 'BH.png'],
            ['id' => 26, 'nama' => 'Bahamas', 'iso1' => 'BHS', 'iso2' => 'BS', 'flag' => 'BS.png'],
            ['id' => 27, 'nama' => 'Bosnia and Herzegovina', 'iso1' => 'BIH', 'iso2' => 'BA', 'flag' => 'BA.png'],
            ['id' => 28, 'nama' => 'Saint Barthélemy', 'iso1' => 'BLM', 'iso2' => 'BL', 'flag' => 'BL.png'],
            ['id' => 29, 'nama' => 'Belarus', 'iso1' => 'BLR', 'iso2' => 'BY', 'flag' => 'BY.png'],
            ['id' => 30, 'nama' => 'Belize', 'iso1' => 'BLZ', 'iso2' => 'BZ', 'flag' => 'BZ.png'],
            ['id' => 31, 'nama' => 'Bermuda', 'iso1' => 'BMU', 'iso2' => 'BM', 'flag' => 'BM.png'],
            ['id' => 32, 'nama' => 'Bolivia', 'iso1' => 'BOL', 'iso2' => 'BO', 'flag' => 'BO.png'],
            ['id' => 33, 'nama' => 'Brazil', 'iso1' => 'BRA', 'iso2' => 'BR', 'flag' => 'BR.png'],
            ['id' => 34, 'nama' => 'Barbados', 'iso1' => 'BRB', 'iso2' => 'BB', 'flag' => 'BB.png'],
            ['id' => 35, 'nama' => 'Brunei', 'iso1' => 'BRN', 'iso2' => 'BN', 'flag' => 'BN.png'],
            ['id' => 36, 'nama' => 'Bhutan', 'iso1' => 'BTN', 'iso2' => 'BT', 'flag' => 'BT.png'],
            ['id' => 37, 'nama' => 'Bouvet Island', 'iso1' => 'BVT', 'iso2' => 'BV', 'flag' => 'BV.png'],
            ['id' => 38, 'nama' => 'Botswana', 'iso1' => 'BWA', 'iso2' => 'BW', 'flag' => 'BW.png'],
            ['id' => 39, 'nama' => 'Central African Republic', 'iso1' => 'CAF', 'iso2' => 'CF', 'flag' => 'CF.png'],
            ['id' => 40, 'nama' => 'Canada', 'iso1' => 'CAN', 'iso2' => 'CA', 'flag' => 'CA.png'],
            ['id' => 41, 'nama' => 'Cocos [Keeling] Islands', 'iso1' => 'CCK', 'iso2' => 'CC', 'flag' => 'CC.png'],
            ['id' => 42, 'nama' => 'Switzerland', 'iso1' => 'CHE', 'iso2' => 'CH', 'flag' => 'CH.png'],
            ['id' => 43, 'nama' => 'Chile', 'iso1' => 'CHL', 'iso2' => 'CL', 'flag' => 'CL.png'],
            ['id' => 44, 'nama' => 'China', 'iso1' => 'CHN', 'iso2' => 'CN', 'flag' => 'CN.png'],
            ['id' => 45, 'nama' => 'Ivory Coast', 'iso1' => 'CIV', 'iso2' => 'CI', 'flag' => 'CI.png'],
            ['id' => 46, 'nama' => 'Cameroon', 'iso1' => 'CMR', 'iso2' => 'CM', 'flag' => 'CM.png'],
            ['id' => 47, 'nama' => 'Democratic Republic of the Congo', 'iso1' => 'COD', 'iso2' => 'CD', 'flag' => 'CD.png'],
            ['id' => 48, 'nama' => 'Republic of the Congo', 'iso1' => 'COG', 'iso2' => 'CG', 'flag' => 'CG.png'],
            ['id' => 49, 'nama' => 'Cook Islands', 'iso1' => 'COK', 'iso2' => 'CK', 'flag' => 'CK.png'],
            ['id' => 50, 'nama' => 'Colombia', 'iso1' => 'COL', 'iso2' => 'CO', 'flag' => 'CO.png'],
            ['id' => 51, 'nama' => 'Comoros', 'iso1' => 'COM', 'iso2' => 'KM', 'flag' => 'KM.png'],
            ['id' => 52, 'nama' => 'Cape Verde', 'iso1' => 'CPV', 'iso2' => 'CV', 'flag' => 'CV.png'],
            ['id' => 53, 'nama' => 'Costa Rica', 'iso1' => 'CRI', 'iso2' => 'CR', 'flag' => 'CR.png'],
            ['id' => 54, 'nama' => 'Cuba', 'iso1' => 'CUB', 'iso2' => 'CU', 'flag' => 'CU.png'],
            ['id' => 55, 'nama' => 'Curacao', 'iso1' => 'CUW', 'iso2' => 'CW', 'flag' => 'CW.png'],
            ['id' => 56, 'nama' => 'Christmas Island', 'iso1' => 'CXR', 'iso2' => 'CX', 'flag' => 'CX.png'],
            ['id' => 57, 'nama' => 'Cayman Islands', 'iso1' => 'CYM', 'iso2' => 'KY', 'flag' => 'KY.png'],
            ['id' => 58, 'nama' => 'Cyprus', 'iso1' => 'CYP', 'iso2' => 'CY', 'flag' => 'CY.png'],
            ['id' => 59, 'nama' => 'Czech Republic', 'iso1' => 'CZE', 'iso2' => 'CZ', 'flag' => 'CZ.png'],
            ['id' => 60, 'nama' => 'Germany', 'iso1' => 'DEU', 'iso2' => 'DE', 'flag' => 'DE.png'],
            ['id' => 61, 'nama' => 'Djibouti', 'iso1' => 'DJI', 'iso2' => 'DJ', 'flag' => 'DJ.png'],
            ['id' => 62, 'nama' => 'Dominica', 'iso1' => 'DMA', 'iso2' => 'DM', 'flag' => 'DM.png'],
            ['id' => 63, 'nama' => 'Denmark', 'iso1' => 'DNK', 'iso2' => 'DK', 'flag' => 'DK.png'],
            ['id' => 64, 'nama' => 'Dominican Republic', 'iso1' => 'DOM', 'iso2' => 'DO', 'flag' => 'DO.png'],
            ['id' => 65, 'nama' => 'Algeria', 'iso1' => 'DZA', 'iso2' => 'DZ', 'flag' => 'DZ.png'],
            ['id' => 66, 'nama' => 'Ecuador', 'iso1' => 'ECU', 'iso2' => 'EC', 'flag' => 'EC.png'],
            ['id' => 67, 'nama' => 'Egypt', 'iso1' => 'EGY', 'iso2' => 'EG', 'flag' => 'EG.png'],
            ['id' => 68, 'nama' => 'Eritrea', 'iso1' => 'ERI', 'iso2' => 'ER', 'flag' => 'ER.png'],
            ['id' => 69, 'nama' => 'Western Sahara', 'iso1' => 'ESH', 'iso2' => 'EH', 'flag' => 'EH.png'],
            ['id' => 70, 'nama' => 'Spain', 'iso1' => 'ESP', 'iso2' => 'ES', 'flag' => 'ES.png'],
            ['id' => 71, 'nama' => 'Estonia', 'iso1' => 'EST', 'iso2' => 'EE', 'flag' => 'EE.png'],
            ['id' => 72, 'nama' => 'Ethiopia', 'iso1' => 'ETH', 'iso2' => 'ET', 'flag' => 'ET.png'],
            ['id' => 73, 'nama' => 'Finland', 'iso1' => 'FIN', 'iso2' => 'FI', 'flag' => 'FI.png'],
            ['id' => 74, 'nama' => 'Fiji', 'iso1' => 'FJI', 'iso2' => 'FJ', 'flag' => 'FJ.png'],
            ['id' => 75, 'nama' => 'Falkland Islands', 'iso1' => 'FLK', 'iso2' => 'FK', 'flag' => 'FK.png'],
            ['id' => 76, 'nama' => 'France', 'iso1' => 'FRA', 'iso2' => 'FR', 'flag' => 'FR.png'],
            ['id' => 77, 'nama' => 'Faroe Islands', 'iso1' => 'FRO', 'iso2' => 'FO', 'flag' => 'FO.png'],
            ['id' => 78, 'nama' => 'Micronesia', 'iso1' => 'FSM', 'iso2' => 'FM', 'flag' => 'FM.png'],
            ['id' => 79, 'nama' => 'Gabon', 'iso1' => 'GAB', 'iso2' => 'GA', 'flag' => 'GA.png'],
            ['id' => 80, 'nama' => 'United Kingdom', 'iso1' => 'GBR', 'iso2' => 'GB', 'flag' => 'GB.png'],
            ['id' => 81, 'nama' => 'Georgia', 'iso1' => 'GEO', 'iso2' => 'GE', 'flag' => 'GE.png'],
            ['id' => 82, 'nama' => 'Guernsey', 'iso1' => 'GGY', 'iso2' => 'GG', 'flag' => 'GG.png'],
            ['id' => 83, 'nama' => 'Ghana', 'iso1' => 'GHA', 'iso2' => 'GH', 'flag' => 'GH.png'],
            ['id' => 84, 'nama' => 'Gibraltar', 'iso1' => 'GIB', 'iso2' => 'GI', 'flag' => 'GI.png'],
            ['id' => 85, 'nama' => 'Guinea', 'iso1' => 'GIN', 'iso2' => 'GN', 'flag' => 'GN.png'],
            ['id' => 86, 'nama' => 'Guadeloupe', 'iso1' => 'GLP', 'iso2' => 'GP', 'flag' => 'GP.png'],
            ['id' => 87, 'nama' => 'Gambia', 'iso1' => 'GMB', 'iso2' => 'GM', 'flag' => 'GM.png'],
            ['id' => 88, 'nama' => 'Guinea-Bissau', 'iso1' => 'GNB', 'iso2' => 'GW', 'flag' => 'GW.png'],
            ['id' => 89, 'nama' => 'Equatorial Guinea', 'iso1' => 'GNQ', 'iso2' => 'GQ', 'flag' => 'GQ.png'],
            ['id' => 90, 'nama' => 'Greece', 'iso1' => 'GRC', 'iso2' => 'GR', 'flag' => 'GR.png'],
            ['id' => 91, 'nama' => 'Grenada', 'iso1' => 'GRD', 'iso2' => 'GD', 'flag' => 'GD.png'],
            ['id' => 92, 'nama' => 'Greenland', 'iso1' => 'GRL', 'iso2' => 'GL', 'flag' => 'GL.png'],
            ['id' => 93, 'nama' => 'Guatemala', 'iso1' => 'GTM', 'iso2' => 'GT', 'flag' => 'GT.png'],
            ['id' => 94, 'nama' => 'French Guiana', 'iso1' => 'GUF', 'iso2' => 'GF', 'flag' => 'GF.png'],
            ['id' => 95, 'nama' => 'Guam', 'iso1' => 'GUM', 'iso2' => 'GU', 'flag' => 'GU.png'],
            ['id' => 96, 'nama' => 'Guyana', 'iso1' => 'GUY', 'iso2' => 'GY', 'flag' => 'GY.png'],
            ['id' => 97, 'nama' => 'Hong Kong', 'iso1' => 'HKG', 'iso2' => 'HK', 'flag' => 'HK.png'],
            ['id' => 98, 'nama' => 'Heard Island and McDonald Islands', 'iso1' => 'HMD', 'iso2' => 'HM', 'flag' => 'HM.png'],
            ['id' => 99, 'nama' => 'Honduras', 'iso1' => 'HND', 'iso2' => 'HN', 'flag' => 'HN.png'],
            ['id' => 100, 'nama' => 'Croatia', 'iso1' => 'HRV', 'iso2' => 'HR', 'flag' => 'HR.png'],
            ['id' => 101, 'nama' => 'Haiti', 'iso1' => 'HTI', 'iso2' => 'HT', 'flag' => 'HT.png'],
            ['id' => 102, 'nama' => 'Hungary', 'iso1' => 'HUN', 'iso2' => 'HU', 'flag' => 'HU.png'],
            ['id' => 103, 'nama' => 'Indonesia', 'iso1' => 'IDN', 'iso2' => 'ID', 'flag' => 'ID.png'],
            ['id' => 104, 'nama' => 'Isle of Man', 'iso1' => 'IMN', 'iso2' => 'IM', 'flag' => 'IM.png'],
            ['id' => 105, 'nama' => 'India', 'iso1' => 'IND', 'iso2' => 'IN', 'flag' => 'IN.png'],
            ['id' => 106, 'nama' => 'British Indian Ocean Territory', 'iso1' => 'IOT', 'iso2' => 'IO', 'flag' => 'IO.png'],
            ['id' => 107, 'nama' => 'Ireland', 'iso1' => 'IRL', 'iso2' => 'IE', 'flag' => 'IE.png'],
            ['id' => 108, 'nama' => 'Iran', 'iso1' => 'IRN', 'iso2' => 'IR', 'flag' => 'IR.png'],
            ['id' => 109, 'nama' => 'Iraq', 'iso1' => 'IRQ', 'iso2' => 'IQ', 'flag' => 'IQ.png'],
            ['id' => 110, 'nama' => 'Iceland', 'iso1' => 'ISL', 'iso2' => 'IS', 'flag' => 'IS.png'],
            ['id' => 111, 'nama' => 'Israel', 'iso1' => 'ISR', 'iso2' => 'IL', 'flag' => 'IL.png'],
            ['id' => 112, 'nama' => 'Italy', 'iso1' => 'ITA', 'iso2' => 'IT', 'flag' => 'IT.png'],
            ['id' => 113, 'nama' => 'Jamaica', 'iso1' => 'JAM', 'iso2' => 'JM', 'flag' => 'JM.png'],
            ['id' => 114, 'nama' => 'Jersey', 'iso1' => 'JEY', 'iso2' => 'JE', 'flag' => 'JE.png'],
            ['id' => 115, 'nama' => 'Jordan', 'iso1' => 'JOR', 'iso2' => 'JO', 'flag' => 'JO.png'],
            ['id' => 116, 'nama' => 'Japan', 'iso1' => 'JPN', 'iso2' => 'JP', 'flag' => 'JP.png'],
            ['id' => 117, 'nama' => 'Kazakhstan', 'iso1' => 'KAZ', 'iso2' => 'KZ', 'flag' => 'KZ.png'],
            ['id' => 118, 'nama' => 'Kenya', 'iso1' => 'KEN', 'iso2' => 'KE', 'flag' => 'KE.png'],
            ['id' => 119, 'nama' => 'Kyrgyzstan', 'iso1' => 'KGZ', 'iso2' => 'KG', 'flag' => 'KG.png'],
            ['id' => 120, 'nama' => 'Cambodia', 'iso1' => 'KHM', 'iso2' => 'KH', 'flag' => 'KH.png'],
            ['id' => 121, 'nama' => 'Kiribati', 'iso1' => 'KIR', 'iso2' => 'KI', 'flag' => 'KI.png'],
            ['id' => 122, 'nama' => 'Saint Kitts and Nevis', 'iso1' => 'KNA', 'iso2' => 'KN', 'flag' => 'KN.png'],
            ['id' => 123, 'nama' => 'South Korea', 'iso1' => 'KOR', 'iso2' => 'KR', 'flag' => 'KR.png'],
            ['id' => 124, 'nama' => 'Kuwait', 'iso1' => 'KWT', 'iso2' => 'KW', 'flag' => 'KW.png'],
            ['id' => 125, 'nama' => 'Laos', 'iso1' => 'LAO', 'iso2' => 'LA', 'flag' => 'LA.png'],
            ['id' => 126, 'nama' => 'Lebanon', 'iso1' => 'LBN', 'iso2' => 'LB', 'flag' => 'LB.png'],
            ['id' => 127, 'nama' => 'Liberia', 'iso1' => 'LBR', 'iso2' => 'LR', 'flag' => 'LR.png'],
            ['id' => 128, 'nama' => 'Libya', 'iso1' => 'LBY', 'iso2' => 'LY', 'flag' => 'LY.png'],
            ['id' => 129, 'nama' => 'Saint Lucia', 'iso1' => 'LCA', 'iso2' => 'LC', 'flag' => 'LC.png'],
            ['id' => 130, 'nama' => 'Liechtenstein', 'iso1' => 'LIE', 'iso2' => 'LI', 'flag' => 'LI.png'],
            ['id' => 131, 'nama' => 'Sri Lanka', 'iso1' => 'LKA', 'iso2' => 'LK', 'flag' => 'LK.png'],
            ['id' => 132, 'nama' => 'Lesotho', 'iso1' => 'LSO', 'iso2' => 'LS', 'flag' => 'LS.png'],
            ['id' => 133, 'nama' => 'Lithuania', 'iso1' => 'LTU', 'iso2' => 'LT', 'flag' => 'LT.png'],
            ['id' => 134, 'nama' => 'Luxembourg', 'iso1' => 'LUX', 'iso2' => 'LU', 'flag' => 'LU.png'],
            ['id' => 135, 'nama' => 'Latvia', 'iso1' => 'LVA', 'iso2' => 'LV', 'flag' => 'LV.png'],
            ['id' => 136, 'nama' => 'Macao', 'iso1' => 'MAC', 'iso2' => 'MO', 'flag' => 'MO.png'],
            ['id' => 137, 'nama' => 'Saint Martin', 'iso1' => 'MAF', 'iso2' => 'MF', 'flag' => 'MF.png'],
            ['id' => 138, 'nama' => 'Morocco', 'iso1' => 'MAR', 'iso2' => 'MA', 'flag' => 'MA.png'],
            ['id' => 139, 'nama' => 'Monaco', 'iso1' => 'MCO', 'iso2' => 'MC', 'flag' => 'MC.png'],
            ['id' => 140, 'nama' => 'Moldova', 'iso1' => 'MDA', 'iso2' => 'MD', 'flag' => 'MD.png'],
            ['id' => 141, 'nama' => 'Madagascar', 'iso1' => 'MDG', 'iso2' => 'MG', 'flag' => 'MG.png'],
            ['id' => 142, 'nama' => 'Maldives', 'iso1' => 'MDV', 'iso2' => 'MV', 'flag' => 'MV.png'],
            ['id' => 143, 'nama' => 'Mexico', 'iso1' => 'MEX', 'iso2' => 'MX', 'flag' => 'MX.png'],
            ['id' => 144, 'nama' => 'Marshall Islands', 'iso1' => 'MHL', 'iso2' => 'MH', 'flag' => 'MH.png'],
            ['id' => 145, 'nama' => 'Macedonia', 'iso1' => 'MKD', 'iso2' => 'MK', 'flag' => 'MK.png'],
            ['id' => 146, 'nama' => 'Mali', 'iso1' => 'MLI', 'iso2' => 'ML', 'flag' => 'ML.png'],
            ['id' => 147, 'nama' => 'Malta', 'iso1' => 'MLT', 'iso2' => 'MT', 'flag' => 'MT.png'],
            ['id' => 148, 'nama' => 'Myanmar [Burma]', 'iso1' => 'MMR', 'iso2' => 'MM', 'flag' => 'MM.png'],
            ['id' => 149, 'nama' => 'Montenegro', 'iso1' => 'MNE', 'iso2' => 'ME', 'flag' => 'ME.png'],
            ['id' => 150, 'nama' => 'Mongolia', 'iso1' => 'MNG', 'iso2' => 'MN', 'flag' => 'MN.png'],
            ['id' => 151, 'nama' => 'Northern Mariana Islands', 'iso1' => 'MNP', 'iso2' => 'MP', 'flag' => 'MP.png'],
            ['id' => 152, 'nama' => 'Mozambique', 'iso1' => 'MOZ', 'iso2' => 'MZ', 'flag' => 'MZ.png'],
            ['id' => 153, 'nama' => 'Mauritania', 'iso1' => 'MRT', 'iso2' => 'MR', 'flag' => 'MR.png'],
            ['id' => 154, 'nama' => 'Montserrat', 'iso1' => 'MSR', 'iso2' => 'MS', 'flag' => 'MS.png'],
            ['id' => 155, 'nama' => 'Martinique', 'iso1' => 'MTQ', 'iso2' => 'MQ', 'flag' => 'MQ.png'],
            ['id' => 156, 'nama' => 'Mauritius', 'iso1' => 'MUS', 'iso2' => 'MU', 'flag' => 'MU.png'],
            ['id' => 157, 'nama' => 'Malawi', 'iso1' => 'MWI', 'iso2' => 'MW', 'flag' => 'MW.png'],
            ['id' => 158, 'nama' => 'Malaysia', 'iso1' => 'MYS', 'iso2' => 'MY', 'flag' => 'MY.png'],
            ['id' => 159, 'nama' => 'Mayotte', 'iso1' => 'MYT', 'iso2' => 'YT', 'flag' => 'YT.png'],
            ['id' => 160, 'nama' => 'Namibia', 'iso1' => 'NAM', 'iso2' => 'NA', 'flag' => 'NA.png'],
            ['id' => 161, 'nama' => 'New Caledonia', 'iso1' => 'NCL', 'iso2' => 'NC', 'flag' => 'NC.png'],
            ['id' => 162, 'nama' => 'Niger', 'iso1' => 'NER', 'iso2' => 'NE', 'flag' => 'NE.png'],
            ['id' => 163, 'nama' => 'Norfolk Island', 'iso1' => 'NFK', 'iso2' => 'NF', 'flag' => 'NF.png'],
            ['id' => 164, 'nama' => 'Nigeria', 'iso1' => 'NGA', 'iso2' => 'NG', 'flag' => 'NG.png'],
            ['id' => 165, 'nama' => 'Nicaragua', 'iso1' => 'NIC', 'iso2' => 'NI', 'flag' => 'NI.png'],
            ['id' => 166, 'nama' => 'Niue', 'iso1' => 'NIU', 'iso2' => 'NU', 'flag' => 'NU.png'],
            ['id' => 167, 'nama' => 'Netherlands', 'iso1' => 'NLD', 'iso2' => 'NL', 'flag' => 'NL.png'],
            ['id' => 168, 'nama' => 'Norway', 'iso1' => 'NOR', 'iso2' => 'NO', 'flag' => 'NO.png'],
            ['id' => 169, 'nama' => 'Nepal', 'iso1' => 'NPL', 'iso2' => 'NP', 'flag' => 'NP.png'],
            ['id' => 170, 'nama' => 'Nauru', 'iso1' => 'NRU', 'iso2' => 'NR', 'flag' => 'NR.png'],
            ['id' => 171, 'nama' => 'New Zealand', 'iso1' => 'NZL', 'iso2' => 'NZ', 'flag' => 'NZ.png'],
            ['id' => 172, 'nama' => 'Oman', 'iso1' => 'OMN', 'iso2' => 'OM', 'flag' => 'OM.png'],
            ['id' => 173, 'nama' => 'Pakistan', 'iso1' => 'PAK', 'iso2' => 'PK', 'flag' => 'PK.png'],
            ['id' => 174, 'nama' => 'Panama', 'iso1' => 'PAN', 'iso2' => 'PA', 'flag' => 'PA.png'],
            ['id' => 175, 'nama' => 'Pitcairn Islands', 'iso1' => 'PCN', 'iso2' => 'PN', 'flag' => 'PN.png'],
            ['id' => 176, 'nama' => 'Peru', 'iso1' => 'PER', 'iso2' => 'PE', 'flag' => 'PE.png'],
            ['id' => 177, 'nama' => 'Philippines', 'iso1' => 'PHL', 'iso2' => 'PH', 'flag' => 'PH.png'],
            ['id' => 178, 'nama' => 'Palau', 'iso1' => 'PLW', 'iso2' => 'PW', 'flag' => 'PW.png'],
            ['id' => 179, 'nama' => 'Papua New Guinea', 'iso1' => 'PNG', 'iso2' => 'PG', 'flag' => 'PG.png'],
            ['id' => 180, 'nama' => 'Poland', 'iso1' => 'POL', 'iso2' => 'PL', 'flag' => 'PL.png'],
            ['id' => 181, 'nama' => 'Puerto Rico', 'iso1' => 'PRI', 'iso2' => 'PR', 'flag' => 'PR.png'],
            ['id' => 182, 'nama' => 'North Korea', 'iso1' => 'PRK', 'iso2' => 'KP', 'flag' => 'KP.png'],
            ['id' => 183, 'nama' => 'Portugal', 'iso1' => 'PRT', 'iso2' => 'PT', 'flag' => 'PT.png'],
            ['id' => 184, 'nama' => 'Paraguay', 'iso1' => 'PRY', 'iso2' => 'PY', 'flag' => 'PY.png'],
            ['id' => 185, 'nama' => 'Palestine', 'iso1' => 'PSE', 'iso2' => 'PS', 'flag' => 'PS.png'],
            ['id' => 186, 'nama' => 'French Polynesia', 'iso1' => 'PYF', 'iso2' => 'PF', 'flag' => 'PF.png'],
            ['id' => 187, 'nama' => 'Qatar', 'iso1' => 'QAT', 'iso2' => 'QA', 'flag' => 'QA.png'],
            ['id' => 188, 'nama' => 'Réunion', 'iso1' => 'REU', 'iso2' => 'RE', 'flag' => 'RE.png'],
            ['id' => 189, 'nama' => 'Romania', 'iso1' => 'ROU', 'iso2' => 'RO', 'flag' => 'RO.png'],
            ['id' => 190, 'nama' => 'Russia', 'iso1' => 'RUS', 'iso2' => 'RU', 'flag' => 'RU.png'],
            ['id' => 191, 'nama' => 'Rwanda', 'iso1' => 'RWA', 'iso2' => 'RW', 'flag' => 'RW.png'],
            ['id' => 192, 'nama' => 'Saudi Arabia', 'iso1' => 'SAU', 'iso2' => 'SA', 'flag' => 'SA.png'],
            ['id' => 193, 'nama' => 'Sudan', 'iso1' => 'SDN', 'iso2' => 'SD', 'flag' => 'SD.png'],
            ['id' => 194, 'nama' => 'Senegal', 'iso1' => 'SEN', 'iso2' => 'SN', 'flag' => 'SN.png'],
            ['id' => 195, 'nama' => 'Singapore', 'iso1' => 'SGP', 'iso2' => 'SG', 'flag' => 'SG.png'],
            ['id' => 196, 'nama' => 'South Georgia and the South Sandwich Islands', 'iso1' => 'SGS', 'iso2' => 'GS', 'flag' => 'GS.png'],
            ['id' => 197, 'nama' => 'Saint Helena', 'iso1' => 'SHN', 'iso2' => 'SH', 'flag' => 'SH.png'],
            ['id' => 198, 'nama' => 'Svalbard and Jan Mayen', 'iso1' => 'SJM', 'iso2' => 'SJ', 'flag' => 'SJ.png'],
            ['id' => 199, 'nama' => 'Solomon Islands', 'iso1' => 'SLB', 'iso2' => 'SB', 'flag' => 'SB.png'],
            ['id' => 200, 'nama' => 'Sierra Leone', 'iso1' => 'SLE', 'iso2' => 'SL', 'flag' => 'SL.png'],
            ['id' => 201, 'nama' => 'El Salvador', 'iso1' => 'SLV', 'iso2' => 'SV', 'flag' => 'SV.png'],
            ['id' => 202, 'nama' => 'San Marino', 'iso1' => 'SMR', 'iso2' => 'SM', 'flag' => 'SM.png'],
            ['id' => 203, 'nama' => 'Somalia', 'iso1' => 'SOM', 'iso2' => 'SO', 'flag' => 'SO.png'],
            ['id' => 204, 'nama' => 'Saint Pierre and Miquelon', 'iso1' => 'SPM', 'iso2' => 'PM', 'flag' => 'PM.png'],
            ['id' => 205, 'nama' => 'Serbia', 'iso1' => 'SRB', 'iso2' => 'RS', 'flag' => 'RS.png'],
            ['id' => 206, 'nama' => 'South Sudan', 'iso1' => 'SSD', 'iso2' => 'SS', 'flag' => 'SS.png'],
            ['id' => 207, 'nama' => 'São Tomé and Príncipe', 'iso1' => 'STP', 'iso2' => 'ST', 'flag' => 'ST.png'],
            ['id' => 208, 'nama' => 'Suriname', 'iso1' => 'SUR', 'iso2' => 'SR', 'flag' => 'SR.png'],
            ['id' => 209, 'nama' => 'Slovakia', 'iso1' => 'SVK', 'iso2' => 'SK', 'flag' => 'SK.png'],
            ['id' => 210, 'nama' => 'Slovenia', 'iso1' => 'SVN', 'iso2' => 'SI', 'flag' => 'SI.png'],
            ['id' => 211, 'nama' => 'Sweden', 'iso1' => 'SWE', 'iso2' => 'SE', 'flag' => 'SE.png'],
            ['id' => 212, 'nama' => 'Swaziland', 'iso1' => 'SWZ', 'iso2' => 'SZ', 'flag' => 'SZ.png'],
            ['id' => 213, 'nama' => 'Sint Maarten', 'iso1' => 'SXM', 'iso2' => 'SX', 'flag' => 'SX.png'],
            ['id' => 214, 'nama' => 'Seychelles', 'iso1' => 'SYC', 'iso2' => 'SC', 'flag' => 'SC.png'],
            ['id' => 215, 'nama' => 'Syria', 'iso1' => 'SYR', 'iso2' => 'SY', 'flag' => 'SY.png'],
            ['id' => 216, 'nama' => 'Turks and Caicos Islands', 'iso1' => 'TCA', 'iso2' => 'TC', 'flag' => 'TC.png'],
            ['id' => 217, 'nama' => 'Chad', 'iso1' => 'TCD', 'iso2' => 'TD', 'flag' => 'TD.png'],
            ['id' => 218, 'nama' => 'Togo', 'iso1' => 'TGO', 'iso2' => 'TG', 'flag' => 'TG.png'],
            ['id' => 219, 'nama' => 'Thailand', 'iso1' => 'THA', 'iso2' => 'TH', 'flag' => 'TH.png'],
            ['id' => 220, 'nama' => 'Tajikistan', 'iso1' => 'TJK', 'iso2' => 'TJ', 'flag' => 'TJ.png'],
            ['id' => 221, 'nama' => 'Tokelau', 'iso1' => 'TKL', 'iso2' => 'TK', 'flag' => 'TK.png'],
            ['id' => 222, 'nama' => 'Turkmenistan', 'iso1' => 'TKM', 'iso2' => 'TM', 'flag' => 'TM.png'],
            ['id' => 223, 'nama' => 'East Timor', 'iso1' => 'TLS', 'iso2' => 'TL', 'flag' => 'TL.png'],
            ['id' => 224, 'nama' => 'Tonga', 'iso1' => 'TON', 'iso2' => 'TO', 'flag' => 'TO.png'],
            ['id' => 225, 'nama' => 'Trinidad and Tobago', 'iso1' => 'TTO', 'iso2' => 'TT', 'flag' => 'TT.png'],
            ['id' => 226, 'nama' => 'Tunisia', 'iso1' => 'TUN', 'iso2' => 'TN', 'flag' => 'TN.png'],
            ['id' => 227, 'nama' => 'Turkey', 'iso1' => 'TUR', 'iso2' => 'TR', 'flag' => 'TR.png'],
            ['id' => 228, 'nama' => 'Tuvalu', 'iso1' => 'TUV', 'iso2' => 'TV', 'flag' => 'TV.png'],
            ['id' => 229, 'nama' => 'Taiwan', 'iso1' => 'TWN', 'iso2' => 'TW', 'flag' => 'TW.png'],
            ['id' => 230, 'nama' => 'Tanzania', 'iso1' => 'TZA', 'iso2' => 'TZ', 'flag' => 'TZ.png'],
            ['id' => 231, 'nama' => 'Uganda', 'iso1' => 'UGA', 'iso2' => 'UG', 'flag' => 'UG.png'],
            ['id' => 232, 'nama' => 'Ukraine', 'iso1' => 'UKR', 'iso2' => 'UA', 'flag' => 'UA.png'],
            ['id' => 233, 'nama' => 'U.S. Minor Outlying Islands', 'iso1' => 'UMI', 'iso2' => 'UM', 'flag' => 'UM.png'],
            ['id' => 234, 'nama' => 'Uruguay', 'iso1' => 'URY', 'iso2' => 'UY', 'flag' => 'UY.png'],
            ['id' => 235, 'nama' => 'United States', 'iso1' => 'USA', 'iso2' => 'US', 'flag' => 'US.png'],
            ['id' => 236, 'nama' => 'Uzbekistan', 'iso1' => 'UZB', 'iso2' => 'UZ', 'flag' => 'UZ.png'],
            ['id' => 237, 'nama' => 'Vatican City', 'iso1' => 'VAT', 'iso2' => 'VA', 'flag' => 'VA.png'],
            ['id' => 238, 'nama' => 'Saint Vincent and the Grenadines', 'iso1' => 'VCT', 'iso2' => 'VC', 'flag' => 'VC.png'],
            ['id' => 239, 'nama' => 'Venezuela', 'iso1' => 'VEN', 'iso2' => 'VE', 'flag' => 'VE.png'],
            ['id' => 240, 'nama' => 'British Virgin Islands', 'iso1' => 'VGB', 'iso2' => 'VG', 'flag' => 'VG.png'],
            ['id' => 241, 'nama' => 'U.S. Virgin Islands', 'iso1' => 'VIR', 'iso2' => 'VI', 'flag' => 'VI.png'],
            ['id' => 242, 'nama' => 'Vietnam', 'iso1' => 'VNM', 'iso2' => 'VN', 'flag' => 'VN.png'],
            ['id' => 243, 'nama' => 'Vanuatu', 'iso1' => 'VUT', 'iso2' => 'VU', 'flag' => 'VU.png'],
            ['id' => 244, 'nama' => 'Wallis and Futuna', 'iso1' => 'WLF', 'iso2' => 'WF', 'flag' => 'WF.png'],
            ['id' => 245, 'nama' => 'Samoa', 'iso1' => 'WSM', 'iso2' => 'WS', 'flag' => 'WS.png'],
            ['id' => 246, 'nama' => 'Kosovo', 'iso1' => 'XKX', 'iso2' => 'XK', 'flag' => 'XK.png'],
            ['id' => 247, 'nama' => 'Yemen', 'iso1' => 'YEM', 'iso2' => 'YE', 'flag' => 'YE.png'],
            ['id' => 248, 'nama' => 'South Africa', 'iso1' => 'ZAF', 'iso2' => 'ZA', 'flag' => 'ZA.png'],
            ['id' => 249, 'nama' => 'Zambia', 'iso1' => 'ZMB', 'iso2' => 'ZM', 'flag' => 'ZM.png'],
            ['id' => 250, 'nama' => 'Zimbabwe', 'iso1' => 'ZWE', 'iso2' => 'ZW', 'flag' => 'ZW.png'],
        ];
        Country::insert($countries);
    }

}
