@startuml erd

hide circle
skinparam linetype ortho

entity "mdusun" as mdusun {
    *id : int <<auto>>
    --
    kode : varchar(15)
    nama : varchar(200)
    aktif : bit
    id_desa : int <<fk>>
}
entity "mdesa" as mdesa {
    *id : int <<auto>>
    --
    kode : varchar(15)
    nama : varchar(200)
    aktif : bit
}

entity "mkecamatan" as mkecamatan {
    *id : int <<auto>>
    --
    kode : varchar(15)
    nama : varchar(200)
    aktif : bit
}

entity "mkabupaten" as mkabupaten {
    *id : int <<auto>>
    --
    kode : varchar(15)
    nama : varchar(200)
    aktif : bit
}

entity "mprovinsi" as mprovinsi {
    *id : int <<auto>>
    --
    kode : varchar(15)
    nama : varchar(200)
    aktif : bit
}

entity "mkategorilokasikegiatan" as mkategorilokasikegiatan {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mjabatan" as mjabatan {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mjenisbantuan" as mjenisbantuan {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mtargetreinstra" as mtargetreinstra {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mkaitansdg" as mkaitansdg {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mkelompokmarjinal" as mkelompokmarjinal {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}


entity "mpartner" as mpartner {
    *id : int <<auto>>
    --
    nama : varchar(200)
    keterangan : varchar(200)
    aktif : bit
}

entity "msatuan" as msatuan {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "mpendonor" as mpendonor{
    *id : int <<auto>>
    --
    id_pendonorkategori : int <<FK>>
    nama : varchar(200)
    pic : varchar(200)
    email : varchar(200) <null>
    phone : varchar(20) <null>
    aktif : bit
}

entity "mpendonorkategori" as mpendonorkategori{
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "muser" as muser {
    *id : int <<auto>>
    --
    nama : varchar(200)
    id_jabatan : int <<fk>>
    email : varchar(200)
    username : varchar(100)
    password : varchar(100)
    email_verified_at : datetime
    remember_token : varchar(200)
    created_at : datetime
    update_at : datetime
    aktif : bit
}

entity "mrole" as mrole {
    *id : int <<auto>>
    --
    nama : varchar(200)
    created_at : datetime
    update_at : datetime
    aktif : bit
}

entity "muserrole" as muserrole {
    *id : int <<auto>>
    --
    id_user : int <<fk>>
    id_role : int <<fk>>
    created_at : datetime
    update_at : datetime
}

entity "mperan" as mperan {
    *id : int <<auto>>
    --
    nama : varchar(200)
    aktif : bit
}

entity "trprogram" as trprogram {
    *id : int <<auto>>
    --
    nama : varchar (200)
    kode : varchar (50)
    tanggalmulai : datetime
    tanggalselesai : datetime
    totalnilai : decimal
    ekspektasipenerimamanfaat : int
    ekspektasipenerimamanfaatwoman : int
    ekspektasipenerimamanfaatman : int
    ekspektasipenerimamanfaatgirl : int
    ekspektasipenerimamanfaatboy : int
    ekspektasipenerimamanfaattidaklangsung : int
    deskripsiprojek : varchar (500)
    analisamasalah : varchar (500)
    id_user : int <<fk>>
    status: varchar(50)
    created_at : datetime
    update_at : datetime
}

entity "trprogramtargetreinstra" as trprogramtargetreinstra {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_targetreinstra: int <<fk>>
}

entity "trprogramkaitansdg" as trprogramkaitansdg {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_kaitansdg: int <<fk>>
}

entity "trprogramkelompokmarjinal" as trprogramkelompokmarjinal {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_kelompokmarjinal: int <<fk>>
}

entity "trprogrampendonor" as trprogrampendonor {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_pendonor : int <<fk>>
    nilaidonasi : decimal null
}

entity "trprogrampartner" as trprogrampartner {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_partner : int <<fk>>
    email : varchar(200)
    phone : varchar(20)
}

entity "trprogramuser" as trprogramuser {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_user : int <<fk>>
    id_peran : int <<fk>>
}

entity "trprogramgoal" as trprogramgoal {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    deskrispsi : varchar(500)
    indikator : varchar(500)
    target : varchar(500)
}

entity "trprogramobjektif" as trprogramobjektif {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    deskrispsi : varchar(500)
    indikator : varchar(500)
    target : varchar(500)
}

entity "trprogramoutcome" as trprogramoutcome {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    deskrispsi : varchar(500)
    indikator : varchar(500)
    target : varchar(500)
}

entity "trprogramoutcomeoutput" as trprogramoutcomeoutput {
    *id : int <<auto>>
    --
    id_programoutcome : int <<fk>>
    deskrispsi : varchar(500)
    indikator : varchar(500)
    target : varchar(500)
}

entity "trprogramoutcomeoutputactivity" as trprogramoutcomeoutputactivity {
    *id : int <<auto>>
    --
    id_programoutcomeoutput : int <<fk>>
    kode: varchar (50)
    nama : varchar (500)
    deskrispsi : varchar(500)
    indikator : varchar(500)
    target : varchar(500)
    tipe : varhcar (200)
}

entity "trprogramlokasi" as trprogramlokasi {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_provinsi : int <<fk>>
}

entity "trprogramreportschedule" as trprogramreportschedule {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    tanggal : datetime
    keterangan : varchar (500)
}

entity "trprogramdokumen" as trprogramdokumen {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    filepath : varchar (200)
    nama : varchar (200)
    keterangan : varchar (200)
}

entity "trkegiatan" as trkegiatan {
    *id : int <<auto>>
    --
    id_programoutcomeoutputactivity : int <<fk>>
    fasepelaporan : int
    id_jeniskegiatan : int <<fk>>
    id_user : int <<fk>>
    tanggalmulai : datetime
    tanggalselesai : datetime
    status : varchar (50)
    mitra : json null

    deskripsilatarbelakang : text null
    deskripsitujuan : text null
    deskripsikeluaran : text null
    deskripsiyangdikaji : text null

    penerimamanfaatdewasaperempuan : int
    penerimamanfaatdewasalakilaki : int
    penerimamanfaatdewasatotal : int
    penerimamanfaatlansiaperempuan : int
    penerimamanfaatlansialakilaki : int
    penerimamanfaatlansiatotal : int
    penerimamanfaatremajaperempuan : int
    penerimamanfaatremajalakilaki: int
    penerimamanfaatremajatotal : int
    penerimamanfaatanakperempuan : int
    penerimamanfaatanaklakilaki : int
    penerimamanfaatanaktotal : int

    penerimamanfaatdisabilitasperempuan : int
    penerimamanfaatdisabilitaslakilaki: int
    penerimamanfaatdisabilitastotal : int

    penerimamanfaatnondisabilitasperempuan : int
    penerimamanfaatnondisabilitaslakilaki : int
    penerimamanfaatnondisabilitastotal : int

    penerimamanfaatmarjinalperempuan : int
    penerimamanfaatmarjinallakilaki : int
    penerimamanfaatmarjinaltotal : int

    penerimamanfaatperempuantotal : int
    penerimamanfaatlakilakitotal : int
    penerimamanfaattotal : int
}

entity "mjeniskegiatan" as mjeniskegiatan {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "msektor" as msektor {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "trkegiatansektor" as trkegiatansektor {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    id_sektor : int <<fk>>
}

entity "trkegiatanlokasi" as trkegiatanlokasi {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    id_desa : int <<fk>>
    lokasi : text null
    long : decimal (9,6) null
    lat : decimal (9,6) null
}

entity "trkegiatanassessment" as trkegiatanassessment {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    assessmentyangterlibat: text null
    assessmenttemuan : text null
    assessmenttambahan : bit
    assessmenttambahan_ket : text null
    assessmentkendala : text null
    assessmentisu : text null
    assessmentpembelajaran : text null
}

entity "trkegiatansosialisasi" as trkegiatansosialisasi {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    sosialisasiyangterlibat : text null
    sosialisasitemuan : text null
    sosialisasitambahan : bit
    sosialisasitambahan_ket : text null
    sosialisasikendala : text null
    sosialisasiisu : text null
    sosialisasipembelajaran : text null
}

entity "trkegiatanpelatihan" as trkegiatanpelatihan {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    pelatihanpelatih : text null
    pelatihanhasil : text null
    pelatihandistribusi : bit
    pelatihandistribusi_ket : text null
    pelatihanrencana : text null
    pelatihanunggahan : bit
    pelatihanisu : text null
    pelatihanpembelajaran : text null
}

entity "trkegiatanpembelanjaan" as trkegiatanpembelanjaan {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    pembelanjaandetailbarang : text null
    pembelanjaanmulai : datetime null
    pembelanjaanselesai : datetime null
    pembelanjaandistribusimulai : datetime null
    pembelanjaandistribusiselesai : datetime null
    pembelanjaanterdistribusi : bit
    pembelanjaanakandistribusi : bit
    pembelanjaanakandistribusi_ket : text null
    pembelanjaankendala : varchar (500) null
    pembelanjaanisu : text null
    pembelanjaanpembelajaran : text null
}

entity "trkegiatanpengembangan" as trkegiatanpengembangan {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    pengembanganjeniskomponen : text null
    pengembanganberapakomponen : text null
    pengembanganlokasikomponen : text null
    pengembanganyangterlibat : text null
    pengembanganrencana : text null
    pengembangankendala : text null
    pengembanganisu : text null
    pengembanganpembelajaran : text null
}

entity "trkegiatankampanye" as trkegiatankampanye {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    kampanyeyangdikampanyekan : text null
    kampanyejenis : text null
    kampanyebentukkegiatan : text null
    kampanyeyangterlibat : text null
    kampanyeyangdisasar : text null
    kampanyejangkauan : text null
    kampanyerencana : text null
    kampanyekendala : text null
    kampanyeisu : text null
    kampanyepembelajaran : text null
}

entity "trkegiatanpemetaan" as trkegiatanpemetaan {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    pemetaanyangdihasilkan : text null
    pemetaanluasan : text null
    pemetaanunit : text null
    pemetaanyangterlibat : text null
    pemetaanrencana : text null
    pemetaanisu : text null
    pemetaanpembelajaran : text null
}

entity "trkegiatanmonitoring" as trkegiatanmonitoring {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    monitoringyangdipantau : text null
    monitoringdata : text null
    monitoringyangterlibat : text null
    monitoringmetode : text null
    monitoringhasil : text null
    monitoringkegiatanselanjutnya : bit
    monitoringkegiatanselanjutnya_ket : text null
    monitoringkendala : text null
    monitoringisu : text null
    monitoringpembelajaran : text null
}

entity "trkegiatankunjungan" as trkegiatankunjungan {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    kunjunganlembaga : text null
    kunjunganpeserta : text null
    kunjunganyangdilakukan : text null
    kunjunganhasil : text null
    kunjunganpotensipendapatan : text null
    kunjunganrencana : text null
    kunjungankendala : text null
    kunjunganisu : text null
    kunjunganpembelajaran : text null
}

entity "trkegiatankonsultasi" as trkegiatankonsultasi {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    konsultasilembaga : text null
    konsultasikomponen : text null
    konsultasiyangdilakukan : text null
    konsultasihasil : text null
    konsultasipotensipendapatan : text null
    konsultasirencana : text null
    konsultasikendala : text null
    konsultasiisu : text null
    konsultasipembelajaran : text null
}

entity "trkegiatanlainnya" as trkegiatanlainnya {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    lainnyamengapadilakukan : text null
    lainnyadampak : text null
    lainnyasumberpendanaan : text null
    lainnyasumberpendanaan_ket : text null
    lainnyayangterlibat : text null
    lainnyarencana : text null
    lainnyakendala : text null
    lainnyaisu : text null
    lainnyapembelajaran : text null
}

entity "trkegiatandokumen" as trkegiatandokumen {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    filepath : varchar (200)
    nama : varchar (200)
    keterangan : text
}   

entity "trkegiatanpenulis" as trkegiatanpenulis {
    *id : int <<auto>>
    --
    id_kegiatan : int <<fk>>
    id_user : int <<fk>>
    id_peran : int <<fk>>
}

entity "trmealstargetprogress" as trmealstargetprogress {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    tanggal : datetime
}

entity "trmealstargetprogressdetail" as trmealstargetprogressdetail {
    *id : int <<auto>>
    --
    id_mealstargetprogress : int <<fk>>
    id_target : int
    tipe : varchar (50)
    achievments : varchar (500) null
    progress : int null
    persentasecomplete : decimal null
    status : varchar (50)
    challenges : text null
    mitigation : text null
    risk : varchar (50) null
    notes : text null
}

entity "trmealspenerimamanfaat" as trmealspenerimamanfaat {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_user : int <<fk>>
    nama : varchar (200)
    jeniskelamin : varchar (50)
    rt : varchar(200)
    rw : varchar(200)
    id_dusun: int <<fk>>
    notelp : varchar (20)
    id_jeniskelompok : int <<fk>>
    umur : int
}

entity "trmealspenerimamanfaatactivity" as trmealspenerimamanfaatactivity {
    *id : int <<auto>>
    --
    id_mealspenerimamanfaat : int <<fk>>
    id_programoutcomeoutputactivity : int <<fk>>
    checked : bit
}

entity "trmealspenerimamanfaatkelompokmarjinal" as trmealspenerimamanfaatkelompokmarjinal {
    *id : int <<auto>>
    --
    id_mealspenerimamanfaat : int <<fk>>
    id_kelompokmarjinal : int <<fk>>    
}

entity "trmealspenerimamanfaatdisabilitas" as trmealspenerimamanfaatdisabilitas {
    *id : int <<auto>>
    --
    id_mealspenerimamanfaat : int <<fk>>
    id_disabilitas : int <<fk>>    
}

entity "mdisabilitas" as mdisabilitas {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "mjeniskelompok" as mjeniskelompok {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "trmealskomponenmodel" as trmealskomponenmodel {
    *id : int <<auto>>
    --
     id_program : int <<fk>>
     id_komponenmodel : int <<fk>>
     id_targetreinstra: int <<fk>> null
     totaljumlah : int
}

entity "trmealskomponenmodellokasi" as trmealskomponenmodellokasi {
    *id : int <<auto>>
    --
     id_mealskomponenmodel : int <<fk>>
     id_dusun : int <<fk>> null
     id_desa : int <<fk>> null
     id_kecamatan : int <<fk>> null
     id_kabupaten : int <<fk>> null
     id_provinsi : int <<fk>> null
     long : decimal (9,6) null
     lat : decimal (9,6) null
     id_satuan: int <<fk>>
     jumlah: int
}

entity "mkomponenmodel" as mkomponenmodel {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "trmealsfrm" as trmealsfrm {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_userpenerima : int <<fk>> null
    id_jabatanpenerima : int <<fk>> null
    id_userhandler : int <<fk>> null
    id_jabatanhandler : int <<fk>> null
    id_sortofcomplains : int <<fk>> null
    tanggalregistrasi : datetime
    umur : int null
    jeniskelamin : varchar (50) null
    statuskomplain : varchar (50) null
    notelp : varchar (20) null
    alamat : varchar (500) null
    notelppenerima : varchar (20) null
    channels : varchar (100) null
    channelslainnya : varchar (100) null
    kategorikomplain : varchar (100) null
    deskripsikomplain : text null
    tanggalselesai : datetime null
    notelphandler : varchar (20) null
    deskripsi : text null
}

entity "msortofcomplaints" as msortofcomplaints {
    *id : int <<auto>>
    --
    nama : varchar (500)
}

entity "trmealsqb" as trmealsqb {
    *id : int <<auto>>
    --
    id_program : int <<fk>>
    id_typeactivity : int <<fk>>
    id_programoutcomeoutputactivity : int <<fk>>
    id_desa : int <<fk>>
    tanggalimplementasi : datetime
    id_userhandler : int <<fk>>
    id_usercompiler : int <<fk>>
    score : decimal
    catatanevaluasi : varchar (500)
    area : varchar (500)
}

entity "mtypeactivity" as mtypeactivity {
    *id : int <<auto>>
    --
    nama : varchar (200)
}

entity "trmealspreposttest" as trmealspreposttest {
    *id : int <<auto>>
    --
    id_programoutcomeoutputactivity : int <<fk>>
    id_desa: int <<fk>>
    id_user : int <<fk>>
    nama : varchar (200)
    jeniskelamin : varchar (50)
    notelp : varchar (20)
    trainingname : varchar (200)
    tanggal : datetime
    prescore : int
    filedbytraineepre : bit
    postscore : int
    filedbytraineepost : bit
    valuechange : int
}

entity "trlog" as trlog {
    *id : int <<auto>>
    --
    tanggal : datetime
    ipaddress : varchar (100)
    useragent : varchar (500)
    host : varchar (200)
    menu : varchar (100)
    action : varchar (50)
    id_user : int <<fk>>
}

mdusun }o--|| mdesa
muserrole }o--|| muser
muserrole }o--|| mrole
mpendonor }o--|| mpendonorkategori
trprogram }o--|| mkelompokmarjinal
trprogram }o--|| mtargetreinstra
trprogram }o--|| mkaitansdg
trprogram }o--|| muser
trprogrampendonor }o--|| trprogram
trprogrampendonor }o--|| mpendonor
trprogrampartner }o--|| trprogram
trprogrampartner }o--|| mpartner
trprogramuser }o--|| trprogram
trprogramuser }o--|| muser
trprogramuser }o--|| mjabatan
trprogramgoal }o--|| trprogram
trprogramobjektif }o--|| trprogram
trprogramoutcome }o--|| trprogram
trprogramlokasi }o--|| trprogram
trprogramlokasi }o--|| mprovinsi
trprogramreportschedule }o--|| trprogram
trprogramdokumen }o--|| trprogram
trkegiatan }o--|| trprogram
trkegiatanpeserta }o--|| trkegiatan
trkegiatandokumen }o--|| trkegiatan
trkegiatan }o--|| mdusun
trevaluasi }o--|| mdusun
trevaluasi }o--|| mpartner
trevaluasi }o--|| trprogram
trevaluasi }o--|| muser
trevaluasidokumen }o--|| trevaluasi
trprogramtargetreinstra }o--|| trprogram
trprogramtargetreinstra }o--|| mtargetreinstra
trprogramkaitansdg }o--|| trprogram
trprogramkaitansdg }o--|| mkaitansdg
trprogramkelompokmarjinal }o--|| trprogram
trprogramkelompokmarjinal }o--|| mkelompokmarjinal
mpendonor }o--|| mpendonorkategori
trevaluasi }o--|| muser
trkegiatanpesertamarjinal }o--|| mkelompokmarjinal
trevaluasidokumen }o--|| trevaluasi
trkegiatan }o--|| msatuan
trprogramuser }o--|| mperan
trkegiatanpenulis }o--|| mperan
trkegiatanpenulis }o--|| trkegiatan
trkegiatanpenulis }o--|| muser
trkegiatan }o--|| mjenisbantuan
trkegiatan }o--|| mkategorilokasikegiatan
trprogramoutcomeoutput }o--|| trprogramoutcome
trprogramoutcomeoutputactivity }o--|| trprogramoutcomeoutput
trkegiatan }o--|| trprogramoutcomeoutputactivity
trlog }o--|| muser
@enduml